# Generated by Django 3.2.2 on 2021-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrbe', models.CharField(max_length=200)),
                ('create_date', models.DateField()),
            ],
        ),
    ]
