# Generated by Django 3.2.2 on 2021-05-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='descrbe',
            new_name='describe',
        ),
    ]
