# Generated by Django 3.2.2 on 2021-05-19 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210518_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
